#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["pillow>=10", "numpy>=1.24"]
# ///
"""Procedural graphics and sounds for the Portal Guns mod.

Every PNG and OGG the mod ships (graphics/, sound/, thumbnail.png) is generated by this script, with fixed
seeds, so the art can be tweaked and rebuilt in one go:

    uv run tools/gen_assets.py            # or: python3 tools/gen_assets.py  (needs pillow + numpy, ffmpeg)

Sizes follow the prototypes in portal-guns/prototypes/*.lua; tools/check_assets.py verifies they match.
"""
from __future__ import annotations

import math
import shutil
import subprocess
import tempfile
import wave
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "portal-guns"
GFX = MOD / "graphics"
SND = MOD / "sound"

PALETTES = {
    "blue": {"deep": (3, 12, 42), "mid": (24, 110, 238), "light": (120, 205, 255), "hot": (228, 248, 255)},
    "orange": {"deep": (44, 12, 2), "mid": (242, 112, 12), "light": (255, 196, 92), "hot": (255, 244, 218)},
}


# --------------------------------------------------------------------------------------------- helpers

def pal(color: str) -> dict[str, np.ndarray]:
    return {k: np.array(v, dtype=np.float64) / 255.0 for k, v in PALETTES[color].items()}


def rgba(rgb: np.ndarray, alpha: np.ndarray) -> Image.Image:
    """Float RGB (H,W,3) and alpha (H,W) in 0..1 -> straight-alpha RGBA image."""
    rgb = np.clip(rgb, 0, 1)
    alpha = np.clip(alpha, 0, 1)
    rgb = np.where(alpha[..., None] > 1e-4, rgb, 0.0)
    out = np.dstack([rgb, alpha]) * 255.0
    return Image.fromarray(np.round(out).astype(np.uint8), "RGBA")


def premul(img: Image.Image) -> tuple[np.ndarray, np.ndarray]:
    a = np.asarray(img, dtype=np.float64) / 255.0
    return a[..., :3] * a[..., 3:4], a[..., 3]


def unpremul(rgb_p: np.ndarray, alpha: np.ndarray) -> Image.Image:
    alpha = np.clip(alpha, 0, 1)
    rgb = np.where(alpha[..., None] > 1e-4, rgb_p / np.maximum(alpha[..., None], 1e-4), 0.0)
    return rgba(rgb, alpha)


def over(top: Image.Image, bottom: Image.Image) -> Image.Image:
    """Normal 'over' compositing of two straight-alpha RGBA images of the same size."""
    t_rgb, t_a = premul(top)
    b_rgb, b_a = premul(bottom)
    return unpremul(t_rgb + b_rgb * (1 - t_a[..., None]), t_a + b_a * (1 - t_a))


def add_glow(glow: Image.Image, base: Image.Image) -> Image.Image:
    """What the game shows for an additive glow layer drawn over a normal layer, flattened for UI icons."""
    g_rgb, g_a = premul(glow)
    b_rgb, b_a = premul(base)
    return unpremul(np.clip(b_rgb + g_rgb, 0, 1), np.clip(b_a + g_a * 0.85, 0, 1))


def sheet(frames: list[Image.Image], line_length: int) -> Image.Image:
    w, h = frames[0].size
    rows = math.ceil(len(frames) / line_length)
    out = Image.new("RGBA", (w * line_length, h * rows), (0, 0, 0, 0))
    for i, frame in enumerate(frames):
        out.paste(frame, ((i % line_length) * w, (i // line_length) * h))
    return out


def grid(size: int) -> tuple[np.ndarray, np.ndarray]:
    y, x = np.mgrid[0:size, 0:size].astype(np.float64)
    c = (size - 1) / 2
    return x - c, y - c


def save(img: Image.Image, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path, optimize=True)
    print(f"  {path.relative_to(ROOT)}  {img.size[0]}x{img.size[1]}")


# --------------------------------------------------------------------------------------------- portals

PORTAL_FRAMES = 16
PORTAL_SIZE = 192      # px per frame; drawn at scale 0.5 -> 3x3 tiles
PORTAL_RADIUS = 64.0   # px; the rim sits 1 tile from the centre


def portal_frame(color: str, f: int, size: int = PORTAL_SIZE, radius: float = PORTAL_RADIUS):
    """One animation frame -> (body, glow). Body is drawn normally, glow additively (and as glow at night)."""
    p = pal(color)
    dx, dy = grid(size)
    r = np.hypot(dx, dy) / radius          # 1.0 on the rim
    th = np.arctan2(dy, dx)
    phase = 2 * np.pi * f / PORTAL_FRAMES  # every periodic term below completes whole cycles over the loop
    inside = (r < 1.0).astype(np.float64)

    arms = 0.5 + 0.5 * np.cos(3 * (th + 2.8 * r) - phase)        # 3 twisted arms, turning
    flow = 0.5 + 0.5 * np.cos(2 * np.pi * 3.0 * r + phase)       # rings drifting inwards
    depth = np.clip(r, 0, 1) ** 1.6                              # 0 in the middle of the vortex, 1 at the rim

    # Body: a dark vortex that hides the ground, brightening towards the rim.
    body_rgb = p["deep"] * (1 - depth)[..., None] + p["mid"] * depth[..., None]
    body_rgb = body_rgb * (0.72 + 0.28 * flow)[..., None]
    crest = (arms ** 3) * (0.25 + 0.75 * depth)
    body_rgb = body_rgb + (p["light"] - body_rgb) * (0.55 * crest)[..., None]
    edge = np.clip((1.0 - r) * radius / 1.5 + 0.5, 0, 1)         # ~1.5 px anti-aliased edge
    body_a = edge * (0.86 + 0.1 * depth)

    # Glow: a hot rim, an inner bloom, an outer halo, bright arm crests and orbiting sparks.
    shimmer = 0.8 + 0.2 * np.cos(2 * th - phase)
    rim_core = np.exp(-(((r - 1.0) * radius) / 2.2) ** 2) * shimmer
    rim_wide = np.exp(-(((r - 1.0) * radius) / 6.0) ** 2) * 0.55
    halo = np.where(r > 1.0, np.exp(-(r - 1.0) / 0.13), 0.0) * 0.5 * np.clip((1.46 - r) / 0.12, 0, 1)
    bloom = np.exp(-(((r - 0.9) * radius) / 7.0) ** 2) * 0.3 * inside
    crests = (arms ** 12) * depth * inside * 0.5

    sparks = np.zeros_like(r)
    rng = np.random.default_rng({"blue": 11, "orange": 23}[color])
    for _ in range(12):
        laps = rng.choice([-2, -1, 1, 1, 2])                     # whole laps per loop keep it seamless
        angle = rng.uniform(0, 2 * np.pi) + 2 * np.pi * laps * f / PORTAL_FRAMES
        rad = rng.uniform(0.96, 1.18) * radius
        twinkle = 0.55 + 0.45 * np.cos(2 * np.pi * rng.integers(1, 4) * f / PORTAL_FRAMES + rng.uniform(0, 6.3))
        sx, sy = rad * np.cos(angle), rad * np.sin(angle)
        sparks += np.exp(-((dx - sx) ** 2 + (dy - sy) ** 2) / (2 * 1.6 ** 2)) * twinkle

    hot = np.clip(rim_core + sparks, 0, 1)
    glow_i = np.clip(rim_core + rim_wide + halo + bloom + crests + sparks, 0, 1)
    colored = np.clip(rim_wide + halo + bloom + crests, 0, None)
    w_hot = hot / np.maximum(hot + colored, 1e-6)
    glow_rgb = p["light"] * (1 - w_hot)[..., None] + p["hot"] * w_hot[..., None]
    w_mid = np.clip(halo / np.maximum(glow_i, 1e-6), 0, 1)
    glow_rgb = glow_rgb * (1 - w_mid)[..., None] + p["mid"] * w_mid[..., None]
    return rgba(body_rgb, body_a), rgba(glow_rgb, glow_i)


def portal_icon(color: str, size: int) -> Image.Image:
    body, glow = portal_frame(color, 0)
    flat = add_glow(glow, body)
    margin = (PORTAL_SIZE - 150) // 2
    return flat.crop((margin, margin, PORTAL_SIZE - margin, PORTAL_SIZE - margin)).resize((size, size), Image.LANCZOS)


def make_portals() -> None:
    for color in ("blue", "orange"):
        frames = [portal_frame(color, f) for f in range(PORTAL_FRAMES)]
        save(sheet([b for b, _ in frames], 4), GFX / "entity/portal" / f"portal-{color}-body.png")
        save(sheet([g for _, g in frames], 4), GFX / "entity/portal" / f"portal-{color}-glow.png")
        save(portal_icon(color, 64), GFX / "icons" / f"portal-{color}.png")


# --------------------------------------------------------------------------------------------- shots

def make_shots(w: int = 48, h: int = 128) -> None:
    """A streak pointing north (projectiles are rotated to their direction of travel); tinted in game."""
    y, x = np.mgrid[0:h, 0:w].astype(np.float64)
    cx, head = (w - 1) / 2, 34.0
    t = np.clip((y - head) / (h - 10 - head), 0, 1)              # 0 at the head, 1 at the end of the tail
    behind = (y >= head).astype(np.float64)
    blob = np.exp(-((x - cx) ** 2 + (y - head) ** 2) / (2 * 8.5 ** 2))
    tail_w = 6.5 * (1 - t) + 1.2
    tail = np.exp(-((x - cx) ** 2) / (2 * tail_w ** 2)) * (1 - t) ** 1.7 * behind
    glow = np.clip(blob + 0.75 * tail, 0, 1)
    core = np.clip(np.exp(-((x - cx) ** 2 + (y - head) ** 2) / (2 * 3.2 ** 2))
                   + 0.65 * np.exp(-((x - cx) ** 2) / (2 * 1.1 ** 2)) * (1 - t) ** 2.2 * behind, 0, 1)
    white = np.ones((h, w, 3))
    save(rgba(white, glow * 0.9), GFX / "entity/shot/shot-glow.png")
    save(rgba(white, core), GFX / "entity/shot/shot-core.png")


# --------------------------------------------------------------------------------------------- effects

EFFECT_FRAMES = 16
EFFECT_SIZE = 128


def ring_burst_frame(f: int) -> Image.Image:
    dx, dy = grid(EFFECT_SIZE)
    r, th = np.hypot(dx, dy), np.arctan2(dy, dx)
    t = f / (EFFECT_FRAMES - 1)
    radius = 6 + 52 * (1 - (1 - t) ** 2.2)
    thickness = 6.5 * (1 - t) + 1.8
    ring = np.exp(-((r - radius) / thickness) ** 2) * (1 - t) ** 1.2 * (0.72 + 0.28 * np.cos(10 * th + 1.3))
    flash = np.exp(-(r / (16 * (1 + 1.5 * t))) ** 2) * (1 - t) ** 3 * 1.1
    rays = np.exp(-((r - radius * 0.82) / (radius * 0.16 + 1)) ** 2) * (np.cos(8 * th) ** 24) * (1 - t) ** 3 * 0.5
    return rgba(np.ones((EFFECT_SIZE, EFFECT_SIZE, 3)), np.clip(ring + flash + rays, 0, 1))


def sparks_frames() -> list[Image.Image]:
    rng = np.random.default_rng(7)
    n = 30
    angles = rng.uniform(0, 2 * np.pi, n)
    speeds = rng.uniform(2.0, 4.6, n)
    lives = rng.uniform(9, 16, n)
    dx, dy = grid(EFFECT_SIZE)
    frames = []
    for f in range(EFFECT_FRAMES):
        a = np.zeros_like(dx)
        for ang, v, life in zip(angles, speeds, lives):
            if f >= life:
                continue
            k = 1 - f / life
            dist = v * f * (1 - f / (2 * life)) + 3
            ux, uy = math.cos(ang), math.sin(ang)
            length = 2.5 + 3.5 * v * k
            # distance from each pixel to the streak segment [dist - length, dist] along (ux, uy)
            along = dx * ux + dy * uy
            across = -dx * uy + dy * ux
            clamped = np.clip(along, dist - length, dist)
            d2 = (along - clamped) ** 2 + across ** 2
            a += np.exp(-d2 / (2 * 0.9 ** 2)) * k ** 1.2
        a += np.exp(-(np.hypot(dx, dy) / 10) ** 2) * max(0.0, 1 - f / 4) * 1.2
        frames.append(rgba(np.ones((EFFECT_SIZE, EFFECT_SIZE, 3)), np.clip(a, 0, 1)))
    return frames


def make_effects() -> None:
    save(sheet([ring_burst_frame(f) for f in range(EFFECT_FRAMES)], 4), GFX / "entity/effects/ring-burst.png")
    save(sheet(sparks_frames(), 4), GFX / "entity/effects/sparks.png")


# --------------------------------------------------------------------------------------------- the gun

def lerp(a, b, t):
    return tuple(int(round(a[i] + (b[i] - a[i]) * t)) for i in range(len(a)))


def draw_gun(size: int) -> Image.Image:
    """The portal gun, muzzle up-right, on a transparent square. Drawn 4x larger and scaled down."""
    s = 4
    big = size * s
    k = big / 256.0                     # design units: a 256 x 256 canvas
    img = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)

    def P(points):
        return [(px * k, py * k) for px, py in points]

    def box(x0, y0, x1, y1):
        return [x0 * k, y0 * k, x1 * k, y1 * k]

    outline = (24, 26, 32, 255)
    white_hi, white_lo = (250, 251, 252, 255), (178, 184, 194, 255)
    dark, darker = (58, 62, 72, 255), (30, 32, 38, 255)
    blue = PALETTES["blue"]

    # handle
    d.polygon(P([(92, 146), (122, 146), (112, 206), (78, 206)]), fill=outline)
    d.polygon(P([(96, 148), (118, 148), (109, 202), (82, 202)]), fill=dark)
    # rear housing: a white capsule, shaded top to bottom
    d.rounded_rectangle(box(27, 93, 143, 157), radius=29 * k, fill=outline)
    ys = np.linspace(0, 1, big)[:, None, None]
    t = np.clip((ys - 96 / 256) / (58 / 256), 0, 1) ** 1.4
    grad = np.array(white_hi, dtype=np.float64) * (1 - t) + np.array(white_lo, dtype=np.float64) * t
    grad = Image.fromarray(np.broadcast_to(grad, (big, big, 4)).astype(np.uint8), "RGBA")
    mask = Image.new("L", (big, big), 0)
    ImageDraw.Draw(mask).rounded_rectangle(box(30, 96, 140, 154), radius=27 * k, fill=255)
    img.paste(grad, (0, 0), mask)
    d.rounded_rectangle(box(44, 104, 112, 112), radius=4 * k, fill=(255, 255, 255, 255))   # highlight
    d.line(P([(60, 140), (118, 140)]), fill=(150, 156, 168, 255), width=int(3 * k))         # seam
    # black collar with a glowing band
    d.rounded_rectangle(box(132, 90, 170, 160), radius=10 * k, fill=outline)
    d.rounded_rectangle(box(135, 93, 167, 157), radius=8 * k, fill=darker)
    d.rectangle(box(148, 95, 155, 155), fill=blue["mid"] + (255,))
    d.rectangle(box(150, 95, 153, 155), fill=blue["hot"] + (255,))
    # barrel
    d.rounded_rectangle(box(164, 106, 204, 144), radius=8 * k, fill=outline)
    d.rounded_rectangle(box(166, 109, 202, 141), radius=7 * k, fill=dark)
    d.line(P([(170, 115), (198, 115)]), fill=(110, 116, 130, 255), width=int(3 * k))
    # three claws around the muzzle
    d.polygon(P([(190, 104), (214, 86), (238, 92), (218, 100), (204, 114)]), fill=outline)
    d.polygon(P([(190, 146), (214, 164), (238, 158), (218, 150), (204, 136)]), fill=outline)
    d.polygon(P([(194, 107), (214, 91), (230, 94), (215, 101), (204, 111)]), fill=(84, 90, 104, 255))
    d.polygon(P([(194, 143), (214, 159), (230, 156), (215, 149), (204, 139)]), fill=(70, 74, 86, 255))

    # glowing core with a halo
    core = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    cd = ImageDraw.Draw(core)
    cx, cy = 214 * k, 125 * k
    for rad, col in ((30, blue["mid"] + (70,)), (21, blue["mid"] + (150,)), (14, blue["light"] + (255,)),
                     (8, blue["hot"] + (255,))):
        cd.ellipse([cx - rad * k, cy - rad * k, cx + rad * k, cy + rad * k], fill=col)
    core = core.filter(ImageFilter.GaussianBlur(3 * k))
    img.alpha_composite(core)

    img = img.rotate(24, resample=Image.BICUBIC, center=(big / 2, big / 2))
    # Fill the square: crop to the drawing, pad to a square with a small margin, then scale down.
    x0, y0, x1, y1 = img.getchannel("A").point(lambda a: 255 if a > 8 else 0).getbbox()
    side = int(max(x1 - x0, y1 - y0) * 1.04)
    square = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    square.alpha_composite(img.crop((x0, y0, x1, y1)), ((side - (x1 - x0)) // 2, (side - (y1 - y0)) // 2))
    return square.resize((size, size), Image.LANCZOS)


def make_icons() -> None:
    gun = draw_gun(64)
    save(gun, GFX / "icons/portal-gun.png")

    # Technology: the gun between its two portals.
    tech = Image.new("RGBA", (256, 256), (0, 0, 0, 0))
    tech.alpha_composite(portal_icon("blue", 132), (4, 118))
    tech.alpha_composite(portal_icon("orange", 132), (120, 6))
    tech.alpha_composite(draw_gun(220), (18, 22))
    save(tech, GFX / "technology/portal-gun.png")

    # Shortcut "close portals": a light ring with a cross, like the base game's white shortcut glyphs.
    for size in (56, 24):
        s = 8
        big = size * s
        img = Image.new("RGBA", (big, big), (0, 0, 0, 0))
        d = ImageDraw.Draw(img)
        c = (228, 228, 228, 255)
        w = big * 0.11
        m = big * 0.1
        d.ellipse([m, m, big - m, big - m], outline=c, width=int(w))
        q = big * 0.33
        d.line([(q, q), (big - q, big - q)], fill=c, width=int(w * 1.05))
        d.line([(big - q, q), (q, big - q)], fill=c, width=int(w * 1.05))
        save(img.resize((size, size), Image.LANCZOS), GFX / f"icons/shortcut-close-portals-x{size}.png")

    # Mod portal thumbnail (opaque).
    size = 144
    dx, dy = grid(size)
    r = np.hypot(dx, dy) / (size * 0.7)
    bg = np.array([14, 18, 30]) / 255 * (1 - r[..., None]) + np.array([3, 4, 9]) / 255 * r[..., None]
    thumb = rgba(bg, np.ones((size, size)))
    thumb.alpha_composite(portal_icon("blue", 76), (2, 64))
    thumb.alpha_composite(portal_icon("orange", 76), (66, 4))
    thumb.alpha_composite(draw_gun(124), (10, 12))
    save(thumb.convert("RGB"), MOD / "thumbnail.png")


# --------------------------------------------------------------------------------------------- sounds

RATE = 44100


def env(n: int, attack: float, decay: float) -> np.ndarray:
    t = np.arange(n) / RATE
    a = np.clip(t / max(attack, 1e-4), 0, 1)
    return a * np.exp(-t / decay)


def sweep(f0: float, f1: float, n: int, curve: float = 1.0) -> np.ndarray:
    """Phase of a tone gliding from f0 to f1 (exponential glide)."""
    t = np.linspace(0, 1, n) ** curve
    freq = f0 * (f1 / f0) ** t
    return 2 * np.pi * np.cumsum(freq) / RATE


def bandpass_noise(rng, n: int, centre: np.ndarray, q: float = 4.0) -> np.ndarray:
    """White noise through a time-varying resonant band-pass (state-variable filter)."""
    noise = rng.standard_normal(n)
    out = np.zeros(n)
    low = band = 0.0
    damp = 1.0 / q
    for i in range(n):
        f = 2 * math.sin(math.pi * min(centre[i], RATE / 6) / RATE)
        high = noise[i] - low - damp * band
        band += f * high
        low += f * band
        out[i] = band
    return out


def finish(x: np.ndarray, peak: float = 0.8) -> np.ndarray:
    fade = min(len(x), int(0.01 * RATE))
    x = x.copy()
    x[-fade:] *= np.linspace(1, 0, fade)
    return x / (np.max(np.abs(x)) + 1e-9) * peak


def snd_fire(f0: float, f1: float, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    n = int(0.42 * RATE)
    ph = sweep(f0, f1, n, 0.6)
    tone = np.sin(ph + 1.8 * np.sin(ph * 0.5)) * env(n, 0.003, 0.11)
    zap = np.sign(np.sin(ph * 1.5)) * env(n, 0.002, 0.03) * 0.25
    thump = np.sin(sweep(160, 60, n)) * env(n, 0.002, 0.06) * 0.9
    hiss = bandpass_noise(rng, n, np.linspace(5000, 1500, n), 2.0) * env(n, 0.001, 0.04) * 0.15
    return finish(tone + zap + thump + hiss)


def snd_open() -> np.ndarray:
    rng = np.random.default_rng(3)
    n = int(0.9 * RATE)
    t = np.arange(n) / RATE
    swell = np.sin(np.pi * np.clip(t / 0.9, 0, 1)) ** 1.5
    whoosh = bandpass_noise(rng, n, 300 * (6 ** (t / 0.9)), 6.0) * swell * 0.35
    hum = (np.sin(sweep(110, 220, n)) + 0.5 * np.sin(sweep(220, 440, n) * 1.01)) * swell * (1 + 0.2 * np.sin(2 * np.pi * 7 * t))
    shimmer = np.sin(sweep(1800, 2600, n)) * np.sin(2 * np.pi * 13 * t) ** 2 * swell * 0.12
    return finish(whoosh + 0.5 * hum + shimmer, 0.75)


def snd_close() -> np.ndarray:
    rng = np.random.default_rng(4)
    n = int(0.5 * RATE)
    t = np.arange(n) / RATE
    e = env(n, 0.01, 0.14)
    tone = np.sin(sweep(900, 140, n, 0.7)) * e
    suck = bandpass_noise(rng, n, 2500 * (0.15 ** (t / 0.5)), 5.0) * e * 0.5
    pop = np.sin(2 * np.pi * 90 * t) * env(n, 0.002, 0.03) * np.clip((t - 0.38) * 100, 0, 1)
    return finish(tone + suck + pop, 0.7)


def snd_fizzle() -> np.ndarray:
    rng = np.random.default_rng(5)
    n = int(0.55 * RATE)
    t = np.arange(n) / RATE
    crackle = (rng.random(n) < 0.012 * np.exp(-t / 0.2)) * rng.uniform(-1, 1, n)
    crackle = np.convolve(crackle, np.exp(-np.arange(200) / 30), mode="same")
    tone = np.sin(sweep(620, 180, n)) * env(n, 0.003, 0.09) * 0.6
    hiss = bandpass_noise(rng, n, np.full(n, 3500.0), 1.5) * env(n, 0.002, 0.12) * 0.3
    return finish(crackle * 0.8 + tone + hiss, 0.7)


def snd_enter() -> np.ndarray:
    rng = np.random.default_rng(6)
    n = int(0.6 * RATE)
    t = np.arange(n) / RATE
    shape = np.sin(np.pi * np.clip(t / 0.6, 0, 1)) ** 2
    vw = np.sin(sweep(180, 760, n, 1.3)) + 0.6 * np.sin(sweep(185, 770, n, 1.3) * 1.5)
    air = bandpass_noise(rng, n, 600 + 2600 * np.sin(np.pi * t / 0.6), 3.0) * 0.4
    return finish((vw * 0.6 + air) * shape, 0.7)


def snd_denied() -> np.ndarray:
    n = int(0.11 * RATE)
    beep = lambda f: np.sign(np.sin(2 * np.pi * f * np.arange(n) / RATE)) * 0.25 + np.sin(2 * np.pi * f * np.arange(n) / RATE)
    e = env(n, 0.004, 0.05)
    return finish(np.concatenate([beep(520) * e, np.zeros(int(0.03 * RATE)), beep(390) * e]), 0.45)


def write_ogg(samples: np.ndarray, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        wav = Path(tmp) / "x.wav"
        with wave.open(str(wav), "wb") as w:
            w.setnchannels(1)
            w.setsampwidth(2)
            w.setframerate(RATE)
            w.writeframes((np.clip(samples, -1, 1) * 32767).astype("<i2").tobytes())
        subprocess.run(["ffmpeg", "-loglevel", "error", "-y", "-i", str(wav), "-c:a", "libvorbis", "-q:a", "4",
                        "-fflags", "+bitexact", "-flags:a", "+bitexact", "-map_metadata", "-1", str(path)],
                       check=True)
    print(f"  {path.relative_to(ROOT)}  {len(samples) / RATE:.2f}s")


def make_sounds() -> None:
    if not shutil.which("ffmpeg"):
        raise SystemExit("ffmpeg is needed to encode the sounds")
    write_ogg(snd_fire(1500, 520, 1), SND / "portal-fire-blue.ogg")
    write_ogg(snd_fire(1150, 380, 2), SND / "portal-fire-orange.ogg")
    write_ogg(snd_open(), SND / "portal-open.ogg")
    write_ogg(snd_close(), SND / "portal-close.ogg")
    write_ogg(snd_fizzle(), SND / "portal-fizzle.ogg")
    write_ogg(snd_enter(), SND / "portal-enter.ogg")
    write_ogg(snd_denied(), SND / "portal-denied.ogg")


# --------------------------------------------------------------------------------------------- docs

def make_docs() -> None:
    """README previews built from the shipped sheets: the two portals swirling on a grass-coloured ground."""
    media = ROOT / "docs" / "media"
    media.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(0)
    w, h = 2 * PORTAL_SIZE, PORTAL_SIZE
    noise = np.kron(rng.normal(0, 1, (h // 4, w // 4)), np.ones((4, 4)))
    ground = np.clip(np.array([78, 84, 44]) / 255 * (1 + 0.1 * noise[..., None]), 0, 1)
    ground_img = rgba(ground, np.ones((h, w)))
    frames = []
    for f in range(PORTAL_FRAMES):
        frame = ground_img.copy()
        for i, color in enumerate(("blue", "orange")):
            body, glow = portal_frame(color, f)
            layer = Image.new("RGBA", (w, h), (0, 0, 0, 0))
            layer.paste(body, (i * PORTAL_SIZE, 0))
            frame = over(layer, frame)
            glow_layer = Image.new("RGBA", (w, h), (0, 0, 0, 0))
            glow_layer.paste(glow, (i * PORTAL_SIZE, 0))
            frame = add_glow(glow_layer, frame)
        frames.append(frame.convert("RGB"))
    # 16 frames at 0.33 frames per tick is ~48 ticks = 0.8 s per loop in game
    frames[0].save(media / "portals.gif", save_all=True, append_images=frames[1:], duration=50, loop=0)
    print(f"  {(media / 'portals.gif').relative_to(ROOT)}")
    strip = Image.new("RGBA", (64 * 4 + 24 * 3, 64), (0, 0, 0, 0))
    for i, name in enumerate(("portal-gun", "portal-blue", "portal-orange")):
        strip.alpha_composite(Image.open(GFX / "icons" / f"{name}.png").convert("RGBA"), (i * 88, 0))
    strip.alpha_composite(Image.open(GFX / "technology" / "portal-gun.png").convert("RGBA").resize((64, 64), Image.LANCZOS), (3 * 88, 0))
    save(strip, media / "icons.png")


if __name__ == "__main__":
    import sys
    parts = set(sys.argv[1:]) or {"portals", "shots", "effects", "icons", "sounds", "docs"}
    if "portals" in parts:
        make_portals()
    if "shots" in parts:
        make_shots()
    if "effects" in parts:
        make_effects()
    if "icons" in parts:
        make_icons()
    if "sounds" in parts:
        make_sounds()
    if "docs" in parts:
        make_docs()
